# Generated by Django 5.0.6 on 2024-06-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageProcessingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image_url", models.URLField(blank=True, null=True)),
                ("processed_image_url", models.URLField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("processing_start_time", models.DateTimeField(blank=True, null=True)),
                ("processing_end_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
