"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import datetime, timedelta
import base64
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)ph8z-d8-s@2-+h2at%so&l8avhe_4o8n390^woon#acwqcr_v"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api",
    "rest_framework",
    "django_apscheduler",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ENVIRONMENT VARIABLES
DB_ENGINE = os.environ.get("DB_ENGINE") 
DB_NAME = os.environ.get("DB_NAME")
DB_USER = os.environ.get("DB_USER")
DB_PASSWORD = os.environ.get("DB_PASSWORD")
DB_HOST = os.environ.get("DB_HOST")
DB_PORT = os.environ.get("DB_PORT")

AZURE_ACCOUNT_NAME = os.environ.get("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = os.environ.get("AZURE_ACCOUNT_KEY")
AZURE_CONTAINER_NAME = os.environ.get("AZURE_CONTAINER_NAME")
AZURE_STORAGE_CONNECTION_STRING = os.environ.get("AZURE_STORAGE_CONNECTION_STRING")
AZURE_QUEUES_NAME = os.environ.get("AZURE_QUEUES_NAME")

IS_BASE_64 = os.environ.get("IS_BASE_64", None) 


if IS_BASE_64:
    # CONVERT ENVIRONMENT VARIABLES FROM BASE64 TO STRING
    DB_ENGINE = base64.b64decode(DB_ENGINE).decode("utf-8")
    DB_NAME = base64.b64decode(DB_NAME).decode("utf-8")
    DB_USER = base64.b64decode(DB_USER).decode("utf-8")
    DB_PASSWORD = base64.b64decode(DB_PASSWORD).decode("utf-8")
    DB_HOST = base64.b64decode(DB_HOST).decode("utf-8")
    DB_PORT = base64.b64decode(DB_PORT).decode("utf-8")
    AZURE_ACCOUNT_NAME = base64.b64decode(AZURE_ACCOUNT_NAME).decode("utf-8")
    AZURE_ACCOUNT_KEY = base64.b64decode(AZURE_ACCOUNT_KEY).decode("utf-8")
    AZURE_CONTAINER_NAME = base64.b64decode(AZURE_CONTAINER_NAME).decode("utf-8")
    AZURE_STORAGE_CONNECTION_STRING = base64.b64decode(AZURE_STORAGE_CONNECTION_STRING).decode("utf-8")
    AZURE_QUEUES_NAME = base64.b64decode(AZURE_QUEUES_NAME).decode("utf-8")
    
    



# Database
DATABASES = {
    'default': {
        
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME, 
        'USER': DB_USER, 
        'PASSWORD': DB_PASSWORD, 
        'HOST': DB_HOST, 
        'PORT': DB_PORT,  
        
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# # get from env
# AZURE_ACCOUNT_NAME = 
# AZURE_ACCOUNT_KEY = os.environ.get("AZURE_ACCOUNT_KEY")
# AZURE_CONTAINER_NAME = os.environ.get("AZURE_CONTAINER_NAME")
# AZURE_STORAGE_CONNECTION_STRING = os.environ.get("AZURE_STORAGE_CONNECTION_STRING")
# AZURE_QUEUES_NAME = os.environ.get("AZURE_QUEUES_NAME")


# # Django APScheduler
# APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"  # Default
# APSCHEDULER_RUN_NOW_TIMEOUT = 5  # Default, seconds
