apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_ENGINE: ZGphbmdvLmRiLmJhY2tlbmRzLnBvc3RncmVzcWw= # django.db.backends.postgresql
  DB_HOST: cG9zdGdyZXM= # postgres
  DB_PORT: NTQzMg== # 5432
  POSTGRES_DB: ZGF0YWJhc2U=
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW5fcGFzc3dvcmQ=
