name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: message
        run: echo "Building the project"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: message
        run: echo "Testing the project"

  security:
    runs-on: ubuntu-latest

    steps:
      - name: code security
        run: echo "Checking the code security"

      - name: docker security
        run: echo "Checking the docker security"

  merge:
    runs-on: ubuntu-latest
    needs: [build, test, security]

    steps:
      - name: message
        run: echo "Merging the code"

  push-docker:
    runs-on: ubuntu-latest
    needs: [merge]

    steps:
      - name: message
        run: echo "Pushing the docker image"

  deploy:
    runs-on: ubuntu-latest
    needs: [push-docker]

    steps:
      - name: message
        run: echo "Deploying the project"
